"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var professional_1 = require("./professional");
var prof1 = new professional_1.Professional("Anne Hathaway", 40, 56, 1.70, false, "United Stated", 1, "Actriz");
var prof2 = new professional_1.Professional("Morgan Freeman", 85, 79, 1.88, false, "United Stated", 1, "Actor");
var prof3 = new professional_1.Professional("Brad Pitt", 59, 78, 1.80, false, "United Stated", 2, "Actor");
var prof4 = new professional_1.Professional("Margot Robbie", 32, 57, 1.68, false, "Australian", 0, "Actriz");
console.log(prof1.showTheAtributes());
console.log(prof2.showTheAtributes());
console.log(prof3.showTheAtributes());
console.log(prof4.showTheAtributes());
